# Generated by Django 4.2.20 on 2025-04-07 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='type',
        ),
    ]
